apiVersion: batch/v1
kind: CronJob
metadata:
  name: min-backup
  namespace: nginx
spec:
  schedule: "*/1 * * * *"  # every 1 minute
  jobTemplate:
    spec:
      template:
        metadata:
          name: min-backup-pod
          labels:
            app: min-backup
        spec:
          containers:
            - name: min-backup-container
              image: busybox:latest
              command:
                - sh
                - -c
                - >
                  echo "Backup started" ;
                  mkdir -p /backups &&
                  mkdir -p /demo-data &&
                  cp -r /demo-data /backups &&
                  echo "Backup completed" ;
              volumeMounts:
                - name: data-volume
                  mountPath: /demo-data
                - name: backup-volume
                  mountPath: /backups
          restartPolicy: OnFailure
          volumes:
            - name: data-volume
              hostPath:
                path: /demo-data
                type: DirectoryOrCreate
            - name: backup-volume
              hostPath:
                path: /backups
                type: DirectoryOrCreate
